### ISSUE TITLE
How to put this module working on iOS 7 with titanium 3.1.3.GA

### ISSUE THREAD

**Issue by fabiomlferreira** [omorandi/TiAssetsLibrary#1]
I'm unable to put this module working on iOS 7 with titanium 3.1.3.GA, maybe someone can help me.

I want to get a thumbnail of every photos and show all photos on a scroll view. My problem is that I can't get the photos.

Now I have only this code:
var assetslibrary = require('ti.assetslibrary');
Ti.API.info("module is => " + assetslibrary);

assetslibrary.getAssets(function(e){
    Ti.API.info('It Runs');
});

As far as I know this Ti.API.info never runs. 
Can you help with an example?

**Comment by omorandi** [comment]
Hi, the module API doesn't expose a getAssets(callback) method. You have to first get the available groups, then, given a group, get all assets for it:

``` javascript
function success_cb(e) {
    var groups = e.groups;
    if (groups.length > 0) {
        var group1 = groups[0];
        group1.getAssets(processAssets_cb);
    }
}
assetslibrary.getGroups(filter, success_cb, error_cb);
```

see the test application included (ALTestApp)

**Comment by fabiomlferreira** [comment]
Thank you very much. You save my day. Your module is a piece of art.

**Comment by omorandi** [comment]
Glad to help. Thanks
