### ISSUE TITLE
SDK 3.1.3

### ISSUE THREAD

**Issue by mrahmadt** [omorandi/TiAssetsLibrary#2]
Hello

I tried to add TiAssetsLibrary to a new project with SDK 3.1.3 but it's showing this error in TiApp Editor 

"the TiAssetsLibrary module is not supported by Titanium SDK 3.1.3.GA"

any chance to know how to fix it?

**Comment by mrahmadt** [comment]
Just restart Titanium and it worked :)

**Comment by omorandi** [comment]
I love issues that get closed without my intervention ;-)

**Comment by mrahmadt** [comment]
Your plugin is amazing

Thank you very much

I wish if you think about doing same module for phonegap :)

**Comment by omorandi** [comment]
Ha, I don't use PhoneGap, so I think you're out of luck ;-)
Thanks btw.
